### ISSUE TITLE
Sources JAR in Maven

### ISSUE THREAD

**Issue by 0x3333** [perwendel/spark-kotlin#14]
Source JAR in Maven doesn't include the Kotlin sources:

```
# unzip -l spark-kotlin-1.0.0-alpha-sources.jar
Archive:  spark-kotlin-1.0.0-alpha-sources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
       93  05-30-2017 23:37   META-INF/MANIFEST.MF
        0  05-30-2017 23:37   META-INF/
        0  05-30-2017 23:36   dummy/
        0  05-30-2017 23:37   META-INF/maven/
        0  05-30-2017 23:37   META-INF/maven/com.sparkjava/
        0  05-30-2017 23:37   META-INF/maven/com.sparkjava/spark-kotlin/
      920  05-30-2017 23:36   dummy/JavadocDummy.java
     8372  05-30-2017 23:36   META-INF/maven/com.sparkjava/spark-kotlin/pom.xml
      124  05-30-2017 23:37   META-INF/maven/com.sparkjava/spark-kotlin/pom.properties
---------                     -------
     9509                     9 files
```

**Comment by perwendel** [comment]
What I've found both the sources and the javadoc plugins don't support kotlin so for pure kotlin projects dummies need to be provided when delivering to maven central.

**Comment by 0x3333** [comment]
What about the `includes` directive to Apache Maven JAR Plugin?

https://maven.apache.org/plugins/maven-jar-plugin/examples/attached-jar.html

      Specify a list of fileset patterns to be included or excluded by adding <includes>/<include> or <excludes>/<exclude> and add a classifier in your pom.xml.

**Comment by 0x3333** [comment]
Sorry, incorrect URL

https://maven.apache.org/plugins/maven-jar-plugin/examples/include-exclude.html
