### ISSUE TITLE
Possible to group request handlers into controllers?

### ISSUE THREAD

**Issue by pehagg** [perwendel/spark-kotlin#16]
Question/Feature request: I tend to write apps where the code is grouped by feature/package (opposed to group-by-layer) in order to achieve cleaner code, especially when it comes to larger codebases. I'm a newbie to Kotlin and haven't figured a way how to group routes into controllers using spark-kotlin, sparkjava supports this pattern. Is this possible, and if so how? In case it isn't, would it be possible to add support for it to spark-kotlin?

**Comment by v79** [comment]
@pehagg  It is possible; each controller class defines its own routes in the constructor `init { }` block. The main server class just needs to initialise each controller on statup. I've got a toy example working at [https://github.com/v79/kotlin-spark-routes](url) . Adding spark's paths would help with this ( #15 ). I've tried calling `Spark.path("/users/") {... }` but it breaks `staticFiles()` for me.

**Comment by pehagg** [comment]
Thanks @v79, this was exactly what I was looking for! You example was of great help. 

I'll close the issue as #15 is reported separately.
