### ISSUE TITLE
spark/kotlin/Http.kt too big

### ISSUE THREAD

**Issue by IRus** [perwendel/spark-kotlin#2]
In Http.kt few classes and a lot of functions. Consider moving classes in separate file.

**Comment by lallemupp** [comment]
I have done some small refactoring in a new pull request #4

**Comment by perwendel** [comment]
Done in #4. We will keep a clear separation of concerns mindset when moving on. What's the best practice for this in Kotlin we're trying to figure out by trying various concepts
