### ISSUE TITLE
Will it be pushed as a maven artifact for reuse?

### ISSUE THREAD

**Issue by ludoch** [perwendel/spark-kotlin#3]
Will it be pushed as a maven artifact for reuse?
Thanks!

**Comment by IRus** [comment]
@ludoch it's already in central: http://search.maven.org/#search|ga|1|a%3A%22spark-kotlin%22

**Comment by perwendel** [comment]
Already in Maven central!

**Comment by ludoch** [comment]
Amazing! Thanks...
See https://github.com/ludoch/getting-started-java/tree/master/appengine-standard-java8/kotlin-spark-appengine-standard now

**Comment by ludoch** [comment]
Even more official: https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/kotlin-spark-appengine-standard
